pipeline {
  agent any

  stages {
    stage('Clone Repo') {
      steps {
        // Automatically done by Jenkins when using "Pipeline script from SCM"
        //git url: 'https://github.com/Dsusilo18/flask-redis-devops.git'
        echo "Repo cloned automatically"
      }
    }

    stage('Install pip3 (if needed)') {
      steps {
        sh '''
          if ! command -v pip3 > /dev/null; then
            echo "pip3 not found. Installing..."
            sudo apt update && sudo apt install -y python3-pip
          else
            echo "pip3 is already installed."
          fi
        '''
      }    
    }

    stage('Install ansible (if needed)') {
      steps {
        sh '''
          if ! command -v ansible > /dev/null; then
            echo "Ansible not found. Installing..."
            sudo apt update && sudo apt install -y ansible
          else
            echo "Ansibleis already installed."
          fi
        '''
      }
    }

    stage('Install Requirements') {
      steps {
        sh 'pip3 install -r app/requirements.txt'
      }
    }

    stage('Deploy with Ansible') {
      steps {
        sh 'ansible-playbook -i localhost, -c local ansible/playbook.yml --extra-vars "ansible_become_pass=''"'
      }
    }
  }
}
