pipeline {
  agent any

  stages {
    stage('Clone Repo') {
      steps {
        // Automatically done by Jenkins when using "Pipeline script from SCM"
        // git url: 'https://github.com/Dsusilo18/flask-redis-devops.git'
        echo "Repo cloned automatically"
      }
    }

    stage('Get user') { 
      steps {
        sh 'whoami'
        sh 'bash -lc "sudo -n true && echo \"sudo without password works\" || echo \"sudo still requires password\""'
      }
    }
  }
}
