pipeline {
  agent any

  stages {
    stage('Clone Repo') {
      steps {
        // Automatically done by Jenkins when using "Pipeline script from SCM"
        //git url: 'https://github.com/Dsusilo18/flask-redis-devops.git'
        echo "Repo cloned automatically"
      }
    }

    stage('Install Requirements') {
      steps {
        sh 'pip3 install -r app/requirements.txt'
      }
    }

    stage('Deploy with Ansible') {
      steps {
        sh 'ansible-playbook ansible/playbook.yml -i localhost,'
      }
    }
  }
}
