- hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Start App with Docker Compose
      shell: docker-compose up -d
      args:
        chdir: "{{ playbook_dir }}"
